name: diff_image
description: A package to get the difference between two images. Currently supports fetching images from web and from local memory.
version: 1.0.2
homepage: https://github.com/limonadev/diff_image

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  image: ^3.0.2
  meta: ^1.4.0
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.5
